# Generated by Django 5.0.1 on 2024-01-10 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='response_id',
            new_name='id_response',
        ),
    ]
