# Generated by Django 5.0.1 on 2024-01-08 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='username_image',
        ),
    ]
