# Generated by Django 5.0.1 on 2024-01-08 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_response_username_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
